# .github/workflows/auto-merge-dependabot.yml
name: Auto-merge Dependabot
on: pull_request

jobs:
  auto-merge:
    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor
          github-token: ${{ secrets.DEPENDABOT_MERGE_TOKEN }}
