name: Weekly Changelog Updates
on:
  schedule:
    - cron: "0 9 * * 0"
  workflow_dispatch:

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup git identity
        run: |
          git config --global user.email "claude[bot]@users.noreply.github.com"
          git config --global user.name "claude[bot]"

      - name: Copy custom commands
        run: |
          mkdir -p .claude/commands
          cp commands/update-changelog.md .claude/commands/

      - name: Update changelog
        uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          prompt: "/update-changelog"

  update-readme:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup git identity
        run: |
          git config --global user.email "claude[bot]@users.noreply.github.com"
          git config --global user.name "claude[bot]"

      - name: Copy custom commands
        run: |
          mkdir -p .claude/commands
          cp commands/update-readme.md .claude/commands/

      - name: Update readme
        uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          prompt: "/update-readme"
